apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-api-deployment
  labels:
    app: task-tracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-tracker-api
  template:
    metadata:
      labels:
        app: task-tracker-api
    spec:
      containers:
        - name: nodeserver
          image: ghcr.io/ac3m/task-tracker-api:latest
          ports:
            - containerPort: 8000
